import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">ECommerceHomePage</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/login">LogIn</Link>
        </li>
        <li>
          <Link to="/accountdropdownwithaccount">
            AccountDropdownWithaccount
          </Link>
        </li>
        <li>
          <Link to="/categorydropdown">CategoryDropdown</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/checkout">CheckOut</Link>
        </li>
        <li>
          <Link to="/account">Account</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/error">Error</Link>
        </li>
        <li>
          <Link to="/productdetailspage">ProductDetailspage</Link>
        </li>
        <li>
          <Link to="/webmockupeight">WebMockupEight</Link>
        </li>
        <li>
          <Link to="/ecommercehomepagefordribbble">
            ECommerceHomePagefordribbble
          </Link>
        </li>
        <li>
          <Link to="/webmockupthree">WebMockupThree</Link>
        </li>
        <li>
          <Link to="/homepagemockup">Homepagemockup</Link>
        </li>
        <li>
          <Link to="/webmockupten">WebMockupTen</Link>
        </li>
        <li>
          <Link to="/grid">Grid</Link>
        </li>
        <li>
          <Link to="/color">Color</Link>
        </li>
        <li>
          <Link to="/colors">Colors</Link>
        </li>
        <li>
          <Link to="/shadow">Shadow</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
